### ISSUE TITLE
[Question] Is there any API to decompile some function.

### ISSUE THREAD

**Issue by BurningTeng** [avast/retdec#1038]
Code as follow and I use gcc 1.c to generate **a.out** executable file. Is there **any API** to only decompile  function fun()?
`#include <stdio.h>
#include <unistd.h>

int c = 0;
void fun();

int main(){
        while (1) {
             fun();
             sleep(5);
        }
        return 0;
}

void fun() {

         printf("Hello world ");
         printf("%d\n", c++);
}`

**Comment by silverbacknet** [comment]
Yes, it's retdec::decompile() located in src/retdec/retdec.cpp. It'll take some initial setup to use, and you can see examples of that in src/retdec-decompiler/retdec-decompiler.cpp or in the ida plugin's src/idaplugin/retdec.cpp.

There's no real documentation on it, other than the description of the parameters in include/retdec/retdec/retdec.h, and whatever you can find in comments. It did not exist in v4.0, the Python script has since been rewritten to c++, but hasn't made it to an official release yet.

**Comment by PeterMatula** [comment]
Thanks, @silverbacknet for a great answer, these are exactly the places to look to understand how to use RetDec as a library.

As for the documentation... sources are it, we definitely don't get around to documenting it in any other way (and then keeping it actual) any time soon.

As for the release... I would advise to either build `master` yourself or use the latest [automated build](https://github.com/avast/retdec#automated-teamcity-builds). `master` is pretty stable, and again I'm not sure where we get around to doing an official release. However, it is true that moving from Python scripts to a native C++ library would deserve a release.
