### ISSUE TITLE
Everything takes 5.6GB Archlinux/retdec-4.0-2

### ISSUE THREAD

**Issue by isopix** [avast/retdec#1042]
I've build using AUR PKGBUILD and not sure if it should take 5.6GB.
Is it normal?

https://aur.archlinux.org/packages/retdec/
https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=retdec

647M    pkg/retdec/usr/share/retdec/support/generic/yara_patterns/static-code/elf
4,7G    pkg/retdec/usr/share/retdec/support/generic/yara_patterns/static-code/pe

4,2G    pkg/retdec/usr/share/retdec/support/generic/yara_patterns/static-code/pe/32
488M    pkg/retdec/usr/share/retdec/support/generic/yara_patterns/static-code/pe/64

610M    pkg/retdec/usr/share/retdec/support/generic/yara_patterns/static-code/elf/32
38M     pkg/retdec/usr/share/retdec/support/generic/yara_patterns/static-code/elf/64

 - - -

retdec git by somebody else at 20201114_7b437f51-1 took only 1.3GB. Maybe something has changed in retdec, maybe new compiler or compiler flags caused that, but it's waay smaller than mine build

du -hs /usr/share/retdec/support/generic//yara_patterns/static-code/*/*
155M    /usr/share/retdec/support/generic//yara_patterns/static-code/elf/32
9,6M    /usr/share/retdec/support/generic//yara_patterns/static-code/elf/64
782M    /usr/share/retdec/support/generic//yara_patterns/static-code/pe/32
118M    /usr/share/retdec/support/generic//yara_patterns/static-code/pe/64

**Comment by xkubov** [comment]
Hi, we are not maintainers of the AUR PKGBUILD. When we pack our release we don't tend to include the static code signatures that you have listed and that's why the other retdec build you have seen was much smaller.

You can look at what we usually pack in the release here: https://github.com/avast/retdec/releases/download/v4.0/retdec-v4.0-debian-64b.tar.xz
Taken from: https://github.com/avast/retdec/releases/download/v4.0

**Comment by nog642** [comment]
https://github.com/avast/retdec/releases/download/v4.0/retdec-v4.0-debian-64b.tar.xz linked above is literally also 5.6 GB for the exact same reason.
