### ISSUE TITLE
Readme says to use nonexistent retdec-decompiler.exe ?

### ISSUE THREAD

**Issue by DaveInCaz** [avast/retdec#1093]
In the Windows section of the [README ](https://github.com/avast/retdec#windows)it says:

> To decompile a binary file named test.exe, run
> `$RETDEC_INSTALL_DIR\bin\retdec-decompiler.exe test.exe`

However, after unpacking retdec-v4.0-windows-64b.7z I don't find a `retdec-decompiler.exe`. There is however `retdec-decompiler.py`.

I don't know if this is a README typo or an actual issue with the release?

**Comment by PeterMatula** [comment]
This has to do with 2 things:
1) how we use GitHub (or how GitHub is in general)
2) that we didn't do a proper release for a long time.

1) You are probably looking at this [README](https://github.com/avast/retdec) which is from the actual `master`. If you were to build `master`, there would indeed be `retdec-decompiler.exe` and no `retdec-decompiler.py`. If you downloaded `v4.0` you should either be looking at the README in the package you downloaded (if it even contains a README), or [this](https://github.com/avast/retdec/tree/v4.0#windows) README associated with the tag `v4.0`. Both should hopefully correspond to what you see in the package itself.

2) We really ought to do another release. So much has changed from the `v4.0` and I would not recommend using it at this point. I would recommend using the current `master` which you can get [here](https://github.com/avast/retdec#automated-teamcity-builds). In fact, we plan to switch to kinda a rolling release from these `master` builds instead of the [not at all] regular releases like `v4.0` was.

**Comment by DaveInCaz** [comment]
Thank you for the explanation!
