### ISSUE TITLE
What is the purpose of "Demangled" comments?

### ISSUE THREAD

**Issue by SamDecrock** [avast/retdec#564]
Hi,

I decompiled some code and it above each (almost unreadable) function name it reads:

`// Demangled:     SomeClass::NiceNameOfTheFunction()`

Why doesn't the decompiler use that function name instead?

**Comment by s3rvac** [comment]
Hi. The reason is that `SomeClass::NiceNameOfTheFunction()` is not a valid C identifier, so we have decided to put the demangled name of functions in comments and use mangled names in the code (they are valid C identifiers). In general, we strive to make the resulting C code conform to [ISO C99](https://en.wikipedia.org/wiki/C99). If we (ever) support decompilation into C++, we will definitely consider using the demangled names, as they are valid C++ identifiers.

**Comment by SamDecrock** [comment]
Thanks, I understand.
