### ISSUE TITLE
How to debug LLVM IR errors?

### ISSUE THREAD

**Issue by daatno** [avast/retdec#571]
Dear Retdec Devs,

do you know what can be done with llvm::Instruction or llvm::Function to make assertions provide more detail than:
"Running phase: LLVM ( 92.48s )
Instruction does not dominate all uses!
  %14 = load i32, i32* @r6
  %11 = trunc i32 %14 to i8
LLVM ERROR: Broken function found, compilation aborted!"
?
I have searched LLVM classes previously(to enable some other feature), and I found it pretty exhausting, simply because it is huge. Given functionality can reside is several members or parents of a class, even at completely different levels of abstraction.
In particular I would like to print out the address of  the faulty instruction. How would you do that? 

Best regards,
Norbert

**Comment by s3rvac** [comment]
@PeterMatula How do you debug such errors when developing `retdec-bin2llvmir`?

**Comment by PeterMatula** [comment]
1. I don't know how to make LLVM print more information. I don't think you can enable more verbose assert/error messages.
2. This is not LLVM's problem, if decompilation fails with broken LLVM module, it is most likely RetDecs fault.
3. There is no concept of addresses in LLVM - it does not know anything about them, so it cannot tell you this information. See [wiki](https://github.com/avast/retdec/wiki/Capstone2LlvmIr#how-capstone2llvmir-library-works) for more info.

If you encountered this kind of error, create an issue, or add the sample to an existing issue - if there is one.

If you want to look at it yourself...
How would I debug this:
1. RetDec prints phases. I would try to find a phase that screws up - module is OK before the phase and broken after. In this case, it is most likely `-decoder` phase fault.
2. You can try to identify problems by calling `-verify` pass after every phase. You do so by adding the pass to `BIN2LLVMIR_PARAMS` list in `retdec-config.py` script. You can add it anywhere you want, even after every single pass. However, `-verify` does not check all aspects of an LLVM module and therefore it might not find a problem even if there is one.
3. You can inspect LLVM module before/after every pass. Either by using LLVM's options `-print-after-all` / `-print-before-all`/ `-print-after=<PASS_NAME>` / `-print-before=<PASS_NAME>`, or by using RetDec's debug pass `-dump-module`. Again, just add these to `BIN2LLVMIR_PARAMS` list. Add LLVM's options just once anywhere in the list - they dump output to `stdout` and you can redirect it to a file and play with it afterwards. Add `-dump-module` to place(s) where you want to see the current LLVM module - it will create LLVM IR files with the current state named `dump_<N>.ll`.
4. When you have a text representation of an LLVM module, you can grep the instruction LLVM asserted on (e.g. `%14 = load i32, i32* @r6`) and find the address comment before it. E.g.
```
; 0x80483e0
  store volatile i64 134513632, i64* @_asm_program_counter
...
  %14 = load i32, i32* @r6
```
   This gives you an address of the instruction. This information is present only before the pass `-remove-asm-instrs`, afterwards the special instructions marking the original ASM instructions are thrown away.

If you only want to identify an address of instruction where the problem occurs, add `-dump-module` and `-verify` before `-remove-asm-instrs`. Hopefully, `-verify` will detect the problem and then you can grep the instruction in `-dump-module` output. If `-verify` does not find the problem and it asserts only later in LLVM phases, you can try the same thing, but keep in mind, that greping the exact string instruction representation from assert might not be enough, because LLVM module (e.g. variable numbering) could have changed between `-dump-module` and `Running phase: LLVM`. In that case, careful inspection of `print-after-all` can help you identify the correct location.
