### ISSUE TITLE
Error: Loading of the config failed: Missing '}' or the object member name @ line =

### ISSUE THREAD

**Issue by MagnificentS** [avast/retdec#576]
![image](https://user-images.githubusercontent.com/8756646/57814367-b4fb1480-7730-11e9-8e26-395181a118a9.png)
is there anyway to continue from where it stopped?

**Comment by MagnificentS** [comment]
I tried multiple times to decompile just one function and i kept getting not enough resources error

**Comment by s3rvac** [comment]
Hi. Could you please attach or send us the input binary file that you are trying to decompile (`BF.exe`) and the parameters that you have used when running `retdec-decompiler.py`? We will need them to reproduce the issue. If we cannot reproduce the issue, it will be much harder to find what is wrong.

**Comment by MagnificentS** [comment]
How do i send? Link here?

**Comment by s3rvac** [comment]
If you do not want to share it publicly, you can send it privately to my email (it is [in my profile](https://github.com/s3rvac)). This would greatly simplify the debugging. Also, please give us the parameters that you have used when running `retdec-decompiler.py`.

**Comment by s3rvac** [comment]
Thank you for the input binary and PDB file. I have tried to reproduce the issue, but I am unable to do so as the decompilation succeeded in my case. However, it took astonishing 46 hours. This is probably because of the size of the input file (50 MB).

Do you have the `BF.exe.json` file from your failed decompilation? If so, could you please share it with us? We can at least take a look why `retdec-llvmir2hll` was unable to load it.

**Comment by MagnificentS** [comment]
Oops. I deleted it recently due to low disk space. Mine took 40 hours before the crash. I don't know if I have another 40 hours in the next few days to reproduce the json.

**Comment by s3rvac** [comment]
That's alright. I will close the ticket for now as we cannot reproduce the issue. If you ever encounter it again, feel free to re-open it and attach the JSON file.
