### ISSUE TITLE
Add unpacker support for Borland C++ 1995

### ISSUE THREAD

**Issue by cnighswonger** [avast/retdec#671]
retdec: v3.3
OS: Ubuntu 18.04.2 LTS
Python: Python 3.6.8

When attempting to decompile an executable, the decompiler warns:

`RUN: /home/tofu/temp/retdec/bin/retdec-unpacker /home/tofu/APP/app.EXE -o /home/tofu/APP/app.EXE-unpacked.tmp --max-memory-half-ram`
`No matching plugins found for 'Borland C++ 1995'`
`##### Unpacking by using generic unpacker: nothing to do`

And finally:

`Running phase: Initialization ( 0.02s )`
`Running phase: LLVM ( 0.03s )`
`Running phase: Providers initialization ( 0.03s )`
`Running phase: Input binary to LLVM IR decoding ( 0.67s )`
`Error: Decompilation to LLVM IR failed`

**Comment by s3rvac** [comment]
Hi. Are you sure `Borland C++ 1995` is a packer? Seems like a compiler to me. Could you please share with us the `app.EXE` that you are trying to decompile?

**Comment by cnighswonger** [comment]
I've followed up with you via email. Thanks.

**Comment by s3rvac** [comment]
I have taken a look at the binary file that you have sent me. Our signatures suggest that the file has been built with the Borland C++ compiler. This is not a packer, so there is nothing to do with the following message that is produced during unpacking
```
No matching plugins found for 'Borland C++ 1995'
```
Our unpacker takes a look at the detected tools and checks if it has a matching unpacker. If it does not, it simply prints such an informational message. You would receive the same message for files compiled by other compilers. The message simply means that there is nothing to unpack.

As for the decompilation, the file seems to be too big for our decompiler to decompile at once at the moment, and I was unable to get a complete decompilation out of it. The failure that you have reported above (`Error: Decompilation to LLVM IR failed`) seems to be fixed in the current `master`. However, even with the current `master`, the file cannot be decompiled in reasonable time.

What I suggest:
* Use [this RetDec build](https://retdec-tc.avast.com/repository/download/Retdec_WinBuild/.lastSuccessful/package/retdec-master-windows-64b.zip?guest=1) instead (the current `master`).
* Decompile only a part of the file via
    ```
    retdec-decompiler.py --select-ranges RANGE --select-decode-only
    ```
    where `RANGE` is a hexadecimal address range that you would like to decompile (e.g. `0x7d180c-0x7d1833`).

Also, if you have IDA, you can try our [IDA plugin](https://github.com/avast/retdec-idaplugin).

As for the reported issue, I am closing it as there is nothing more to do (see my explanation above). If you have any further questions, let us know (or, if you have a different problem, please open a separate issue).

**Comment by cnighswonger** [comment]
> Use this RetDec build instead (the current master).

Does that come in some flavor of *nix? Ubuntu or Debian preferred.

**Comment by s3rvac** [comment]
Oh, I am sorry, I have blindly assumed that you use Windows. My apologies.

[Here](https://github.com/avast/retdec#automated-teamcity-builds) is a list of all the automated builds that we produce. [One of them is for Ubuntu Bionic (18.04)](https://retdec-tc.avast.com/repository/download/RetDec_LinuxBuild/.lastSuccessful/package/retdec-master-linux-64b.zip?guest=1), which should work also on newer Ubuntu versions or in Debian.
