### ISSUE TITLE
Problem with the retdec-offline binary ninja plugin

### ISSUE THREAD

**Issue by AlexSimpler** [avast/retdec#694]
So when I try the redtec-offline binary ninja plugin using retdecompiler using this command 
```
python c:/Users/test/Documents/retdec/retdec/bin/retdec-decompiler.py --backend-no-debug-comments --cleanup --mode raw --raw-section-vma 0x4b3010 --raw-entry-point 0x4b3010 --arch x86 --endian little --config c:\users\test\appdata\local\temp\tmpfv_yan c:\users\test\appdata\local\temp\tmpe4wgnd
```
 it outputs as error `The filename, directory name, or volume label syntax is incorrect.` and then from binary ninja `failed to decompile function: [Errno 2] No such file or directory: 'c:\\users\\test\\appdata\\local\\temp\\tmpe4wgnd.c'
`

**Comment by s3rvac** [comment]
Hi. Based on the provided description, the issue seems to be in retdec-offline or Binary Ninja plugin rather than in RetDec. As we are not affiliated with retdec-offline nor Binary Ninja, I suggest to open an issue in their bug trackers.

The issue seems to be in incorrect handling of paths by retdec-offline/Binary Ninja. When using RetDec, please do not mix Windows and Linux paths. Use consistently the ones for your environment (e.g. when using `cmd.exe`, use `C:\path\to\file`, but when using MSYS2, use `/c/path/to/file`).

If you still believe that the issue is in RetDec itself, please reopen. I was unable to reproduce the issue by using just RetDec and using proper paths.
