### ISSUE TITLE
Fix calculation of hash for Authenticode signatures

### ISSUE THREAD

**Issue by metthal** [avast/retdec#718]
The current implementation of calculating hash for verifying Authenticode signature in PE files is kinda broken in several parts. Those are:

1. Autheticode structure should be the very last thing in the file but this might not be the case for every binary. It is also very easy to add there some bytes manually. These bytes shouldn't be taken into account when calculating the hash, but we do it right now, which is wrong.

2. From the file header, everything up to `SizeOfHeaders` (apart from checksum and security directory entry) should be hashed. But after that, we should begin with the offset of the very first section which doesn't necessarily have to start at `SizeOfHeaders` offset.

3. Hashed data for sections should be first sorted according to the offset of the section while skipping those with `SizeOfRawData == 0`.

These all might cause some specific samples to report that the hash is invalid when it is in fact valid (and altough basically impossible, also vice-versa). Even if our algorithm works on vast majority of samples, we should take care of these cases, especially for signatures.

**Comment by PeterMatula** [comment]
@metthal Few questions:
* Is this the source you based the info on? https://www.symbolcrash.com/wp-content/uploads/2019/02/Authenticode_PE-1.pdf
* Are we talking about stuff that goes on here? https://github.com/avast/retdec/blob/master/src/fileformat/file_format/pe/pe_format.cpp#L712
* Do you happen to have some [malformed] files that we could test on? If not, I suppose we could manually modify some file. Am I correct?

Coincidentally I was modifying this code just today because of #819. It wasn't the most elegant refactorization, so while solving this we could do it better. But an important thing is to keep in mind, that we don't want OpenSSL in Fileformat's public headers. So either keep everything in sources, or create a new certificate parsing module, but have the header privately in `/src/fileformat` not in `/include/retdec/fileformat`.

**Comment by PeterMatula** [comment]
Related to #380, solve them together.
