### ISSUE TITLE
Installation fails with a "SSL: CERTIFICATE_VERIFY_FAILED" error

### ISSUE THREAD

**Issue by seviezhou** [avast/retdec#800]
When I trying to execute `make install`, the install script got an error when downloading `yarac`:

<img width="992" alt="屏幕快照 2020-07-03 10 51 12" src="https://user-images.githubusercontent.com/15180789/86426827-39389e80-bd1b-11ea-825c-49740e76e2bb.png">

I think this is a certificate verification problem, I think we should add two lines to `support/install-share.py`:

```diff
import sys
import hashlib
import os
import shutil
import tarfile
import urllib.request

+ import ssl
+ ssl._create_default_https_context = ssl._create_unverified_context
```

And the problem can be solved.

**Comment by s3rvac** [comment]
Hi. Before we discuss how to solve this issue, let me point out that **one should not disable certificate verification** because it makes them vulnerable to [man-in-the-middle attacks](https://en.wikipedia.org/wiki/Man-in-the-middle_attack). So, while the above piece of code might work as a workaround, it does not solve the underlying issue and makes you (and anyone who applies it) vulnerable.

**Comment by s3rvac** [comment]
Basically, this error is caused by your system or Python installation not having a proper list of trusted certificates. You will need to fix that. You have written that you use macOS. Could you please try [one of these two solutions](https://timonweb.com/tutorials/fixing-certificate_verify_failed-error-when-trying-requests_html-out-on-mac/)? If none of them works, we can search for another solution. Nevertheless, I do not use macOS, so I will probably just redirect you to another page that describes how to fix your certificate store in macOS.

**Comment by s3rvac** [comment]
[Here](https://medium.com/@yen.hoang.1904/resolve-issue-ssl-certificate-verify-failed-when-trying-to-open-an-url-with-python-on-macos-46d868b44e10) is another page that describes the issue and provides the same two solutions as in the first article that I have provided a link to.

**Comment by seviezhou** [comment]
Thanks, I think the following command will work and is more secure:

```
/Applications/Python\ 3.6/Install\ Certificates.command
```

As suggested by the Python developer: [https://bugs.python.org/issue28150](https://bugs.python.org/issue28150)

**Comment by s3rvac** [comment]
Yes, this is one of the two possible solutions that I have found and linked above. Please, let me know whether it worked for you so we can close this issue.

**Comment by seviezhou** [comment]
Just finishing installing, it works. Maybe this can be added to the installation guidance.
