### ISSUE TITLE
LLVM Bitcode execution problem

### ISSUE THREAD

**Issue by xianggechishi** [avast/retdec#802]
I decompile my test program (generated by Ubuntu gcc) in Ubuntu. The generated test.ll file uses something like: __readfsqword (which belongs to Microsoft's solidified library intrin.h), I am in linux  Re-compiling in Clang can't link this function correctly, how can I deal with it so that it can run under Linux?

It is my console:
koty@ubuntu:~/Desktop/fauxware$ lli fauxware_origin.ll 
LLVM ERROR: Program used external function '__readfsqword' which could not be resolved!

**Comment by silverbacknet** [comment]
This is the clang equivalent: https://clang.llvm.org/docs/LanguageExtensions.html#target-specific-extensions

<blockquote>
**Memory references to specified segments**

Annotating a pointer with address space #256 causes it to be code generated relative to the X86 GS segment register, address space #257 causes it to be relative to the X86 FS segment, and address space #258 causes it to be relative to the X86 SS segment. Note that this is a very very low-level feature that should only be used if you know what you’re doing (for example in an OS kernel).

Here is an example:
```
#define GS_RELATIVE __attribute__((address_space(256)))
int foo(int GS_RELATIVE *P) {
  return *P;
}
```
Which compiles to (on X86-32):
```
_foo:
        movl    4(%esp), %eax
        movl    %gs:(%eax), %eax
        ret
```
You can also use the GCC compatibility macros __seg_fs and __seg_gs for the same purpose. The preprocessor symbols __SEG_FS and __SEG_GS indicate their support.
</blockquote>

**Comment by xianggechishi** [comment]
Thank you for your answer, but what I want to know is how to make xxx.ll code (decompiling by retdec) run?  This low-level function(like : '__readfsqword' ) cannot be found under Linux

**Comment by xkubov** [comment]
Hi, the goal of RetDec is not to produce compilable {.c, .ll} code but it is surely plus. The main goal with decompilation to high-level language and the goal we are still focusing on is to create code that is to someplace readable for binary analysis. In your case, RetDec converts binary instruction load from the FS segment into `__readfsqword`. Intrinsic functions and calls to pseudo functions are included in RetDec so that a user of RetDec can see that on this place in binary was an instruction that had the same semantics as this function. As @silverbacknet there are options on how to manually fix the code if you want to run it.

As this is not a bug I am closing this issue. We can still continue the discussion.

**Comment by silverbacknet** [comment]
I see a use for a --vendor-output clang/gcc/msvc, but that would be such an incredibly huge undertaking and burdensome support task, especially when each has ways of efficiently doing crazy tricks the others can't.
