### ISSUE TITLE
PDBFile image_base should be unsigned long long

### ISSUE THREAD

**Issue by MuellerMP** [avast/retdec#900]
In pdb_file.h
PDBFile::initialize() aswell as PDBFile::parse_sections() should take the image_base as unsigned long long....

idk why it's passed as an int 🙈 RIP 64bit on 32bit archs

**Comment by PeterMatula** [comment]
Fixed in b6442ef57dbd8322dc4a4af56f816cf143e026f9, but...
1. I also changed most other addresses for `uint64_t`.
2. Some structures containing addresses look like taken from some 32-bit specifications and are used in a way that expects 4-byte address entry, these cannot be suddenly changed for 8 byte int. I hope none of those I changed are used in this way, because that woudl cause problems.
3. This entire library (`pdbparser`) is really outdated and not worth maintaining, we should use something else (LLVM?) instead, because any larger changes or improvements are pretty much put of the question.
