### ISSUE TITLE
Questions about symbol table parsing results of retdec

### ISSUE THREAD

**Issue by seviezhou** [avast/retdec#901]
I was trying to use retdec to decompile some relocatable binaries from linux kernel. I was a little bit confused about the function address produced by retdec compared to IDA. For the address of the first function, retdec's result is `0x30`, while IDA's result is `0x0`. I took a look at the bitcode file and found that retdec seems to wrongly place a non-function symbol at address `0x0`. Here is the result of [dm-verity.ko](https://github.com/avast/retdec/files/5611752/dm-verity.ko.zip):

```
define void @rescue_lock() {
dec_label_pc_0:
  %0 = load i64, i64* @rax
  ret void
}

declare i64 @0()

define i64 @verity_prepare_ioctl(i64 %arg1, i64 %arg2) {
dec_label_pc_30:
  store i64 %arg2, i64* @rsi
  store i64 %arg1, i64* @rdi
  %stack_var_0 = alloca i64
  %stack_var_-8 = alloca i64

; 0x30
  store volatile i64 48, i64* @_asm_program_counter
  %0 = call i64 @__fentry__()
  store i64 %0, i64* @rax
  store i64 %0, i64* @rax
```

Here is the result of IDA:

![image](https://user-images.githubusercontent.com/15180789/100535106-ce02e200-3250-11eb-83bc-a20abae62888.png)

**Comment by PeterMatula** [comment]
This is the `objdump -t` entry for `verity_prepare_ioctl`:
```
0000000000000000 l     F .text  0000000000000040 verity_prepare_ioctl
```
It says it is at `0x0` in section `.text`.

This is the `objdump -h` entry for `.text` and a few other sections:
```
Idx Name          Size      VMA               LMA               File off  Algn
  0 .note.gnu.build-id 00000024  0000000000000000  0000000000000000  00000040  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  1 .text         00001e9b  0000000000000000  0000000000000000  00000070  2**4
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE
  2 .init.text    0000002f  0000000000000000  0000000000000000  00001f0b  2**0
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE
  3 .exit.text    00000012  0000000000000000  0000000000000000  00001f3a  2**0
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE
  4 .rodata       00000031  0000000000000000  0000000000000000  00001f50  2**4
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, DATA
...
```
It says all of them are in memory at `0x0`. Which is not possible. But this is generally how relocatable files look like - i.e. sections are not properly mapped in memory.

We don't generally like to place symbols/sections at address `0x0` - it could cause us troubles due to implementation that does not expect symbols at 0x0. This could be made better and more resilient, but we did not do it yet. Therefore we chose a different behavior for such files that IDA. However, I don't think you can say that we placed that symbol _wrongly_, because in these files, there is no _right_ address for it. We can basically choose where we map the `.text` section - positions of symbols within it, and their relations (i.e. calls) should however be reconstructed correctly.

I'm however not an expert on these files, so if you think differently, or there is some valid reason for placing then at `0x0` lets discuss it here.

Also, if there are some reconstruction bugs (e.g. wrong references between functions) caused by this, please open another issue.

**Comment by seviezhou** [comment]
I get it, thank you for your answering!
