### ISSUE TITLE
How to use pre-installed llvm?

### ISSUE THREAD

**Issue by yurivict** [avast/retdec#941]
retdec behins to download llvm (https://github.com/avast/llvm/archive/2a1f3d8a97241c6e91710be8f84cf3cf80c03390.zip) when I have llvm10-10.0.1_5 installed.

How to instruct build to use pre-installed llvm?

**Comment by s3rvac** [comment]
Hi. RetDec requires a [custom version](https://github.com/avast/llvm/) of LLVM with downstream changes that are needed for the decompiler to work properly. Other LLVM versions (e.g. system wide) cannot be used because (1) they do not contain the necessary changes and (2) they might be incompatible (e.g. LLVM 10 is not compatible with LLVM 8, which is what RetDec is currently using).

There is a ticket for adding support for system-wide libraries into RetDec (#356). For some libraries, this has been already done, but not for LLVM. However, frankly, I do not think that it will ever happen for LLVM because of the two reasons above.
