### ISSUE TITLE
how retdec infer types

### ISSUE THREAD

**Issue by Frankenstein-bit** [avast/retdec#993]
how retdec infer array type or other types like struct? If there are any documentation? or give me a  brief description ?

**Comment by PeterMatula** [comment]
There is no documentation on this. But I will try to give you a brief description and links to some academic papers we used.

I would divide it into 3 parts:

1. Data types sources - in some cases we know the exact types of some objects (local/global variables, function parameters/returns) from stuff like debug information, standard library signatures ([DB](https://github.com/avast/retdec/tree/master/support/types) of std functions and their types), etc. In such cases, we apply this info to the objects - i.e. the default object type (integer) is changed to the known data type.
2. Data type inference/propagation - using dataflow analysis, it is possible to propagate types from data type sources and/or infer some more types from the way the program works with data. The basic idea was described in [this](https://link.springer.com/content/pdf/10.1007/3-540-49099-X_14.pdf) paper. Some more papers we used - [simple types](https://link.springer.com/article/10.1134/S0361768809020066), [composite types](https://ieeexplore.ieee.org/document/5601851). However, especially composite types are not solved perfectly. The more aggressive inference was disabled because it was often unreliable and did damage to the output quality. Also, there are known problems with merging of known composite types - e.g. We know there is a structure of size `20` B on address `X`, therefore all the accesses to addresses in `<X, X+20)` range should be transformed to accesses to this structure. But we don't always handle this correctly.
3. It is also possible to parse and use some specialized information present in some samples. E.g. Partial C++ decompilation by parsing virtual tables, RTTI structures, inferring class hierarchies from constructors, etc. as described [here](https://www.researchgate.net/scientific-contributions/A-Fokin-74665836).
